app:
  jolt:
    placementDetailsRequestJoltSpec: /PlacementDetailsRequestJoltSpec.json
    placementDetailsGetResponseJoltSpec: /PlacementDetailsGetResponseJoltSpec.json
    placementDetailsPostResponseJoltSpec: /PlacementDetailsPostResponseJoltSpec.json
