spring:
  mvc:
    throw-exception-if-no-handler: true
  web:   
    resources: 
      add-mappings: false
      
  datasource:
    #url: jdbc:h2:mem:test;MODE=PostgreSQL;INIT=CREATE SCHEMA IF NOT EXISTS student
    url: jdbc:postgresql://34.96.209.61:5432/postgres
    #url: jdbc:postgresql://34.96.209.61:5432/postgres?cloudSqlInstance=hsbc-greensavers-sams-dev:asia-east2:postgres&socketFactory=com.google.cloud.sql.postgres.SocketFactory&useSSL=false
    #url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?cloudSqlInstance=${INSTANCE_CONNECTION_NAME}&socketFactory=com.google.cloud.sql.postgres.SocketFactory&useSSL=false
    username: postgresUserCrud
    password: postgresUserCrud
  jpa:
    open-in-view: false
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show-sql: true
        format-sql: true

  profiles:
    active: dev


server:
  port: 8080
  servlet:
    context-path: /student-assessment-management/placement-details
    

logging:
  level:
    com.pbma.ngo: debug
    
    